# Generated by Django 5.2 on 2025-05-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cabinet_public',
            field=models.BooleanField(default=True),
        ),
    ]
