# Generated by Django 5.2 on 2025-08-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_customuser_cabinet_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='kakao_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
