# Generated by Django 5.2 on 2025-05-24 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(blank=True, choices=[('content', 'Content')], max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('api_thumbnail', models.URLField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('content_title', models.CharField(blank=True, max_length=255, null=True)),
                ('creator', models.JSONField(blank=True, null=True)),
                ('cast', models.JSONField(blank=True, null=True)),
                ('story', models.TextField(blank=True, null=True)),
                ('scenes', models.TextField(blank=True, null=True)),
                ('thoughts', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('companions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecordImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='record_images/')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_urls', to='Records.record')),
            ],
        ),
    ]
